server:
  port: 8083
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/avelardeLaRosa/mcsv-tuto
          search-paths: config-data
